### ISSUE TITLE
No recipe for cooling down Kanthal through chemical bath?

### ISSUE THREAD

**Issue by ExplosiveBunny** [jmoiron/quantum-skies#10]
![image_2024-05-24_100517243](https://github.com/jmoiron/quantum-skies/assets/110858535/d1f5fa73-dc89-4595-adb4-47cc94629d09)
Hello, There is no recipe for cooling down hot kanthal in the chemical bath as the questbook tells the player to,

**Comment by jmoiron** [comment]
This is fixed in latest version, I think there was an issue with the way that other recipes were being removed from the chembath at this time.
