### ISSUE TITLE
No greenhouse recipe, and no tree recipes in it

### ISSUE THREAD

**Issue by windyknight** [jmoiron/quantum-skies#11]
Version 0.1.8

Questbook mentions that the Greenhouse should be the upgrade to the Primitive Woodcutter for wood production, but its recipe map has no registered tree recipes. Also, the Greenhouse cannot be crafted in the first place. Perhaps you forgot to add a recipe?

**Comment by jmoiron** [comment]
This is fixed in 0.2.x 🙇
