### ISSUE TITLE
Entangled Blocks and Covers

### ISSUE THREAD

**Issue by Pyriana** [jmoiron/quantum-skies#19]
Entangled blocks and Covers end up in a bad state on almost every server restart and sometimes randomly throughout the day, causing stuff like primitive blast furnace automation to break, along with a lot of water/fuel depots.

Replacing the entangled block, machine, or pipe fixes it.

The entangled blocks I'm currently using are entangled to supertanks or tom's storage inventory connector to get large inventories.

**Comment by jmoiron** [comment]
I've noticed an issue with pipe-mounted covers losing their ability to see blockstate updates.  If you "grab" them with carry-on and then place them back, it resets them and fixes them.  This is still... quite annoying.

What I've not seen break is a tile entity mounted cover next to an entangled block, so crates, drums, GT machines, etc. These seem to always work.

GTCEu is in the midst of (another) pipenet rewrite, so I'm waiting to see if that fixes things.  I have a feeling that there's something subtle going on with entangled that is causing this, although I've also noticed several issues with `ex nihilo` containers.
