### ISSUE TITLE
Diluted Bastnasite Mud recipe not working

### ISSUE THREAD

**Issue by Pyriana** [jmoiron/quantum-skies#22]
Heya, weekly bug report here lol, I somehow made Samarium Iron Arsenic Oxide wires without completing the Bastnasite side of the lanthanide chains, so I went to walk through the Bastnasite side of the lanthanides and the Diluted Bastnasite Mud recipe in a blast furnace doesn't work, it is supposed to output 11 buckets so I made our output hatch larger just in case but it was already 16. It has no number on the recipe so that's not it and I have hss-g coil blocks and ev power, both higher than what it requires yet the recipe does nothing.

Also I'm happy to show off our base if you let me know how you'd like me to send pictures.

**Comment by Pyriana** [comment]
It looks like this also prevents Incoloy due to yttrium which prevents the vibration safe casing which is used in the planetary core drill.

**Comment by jmoiron** [comment]
Sorry I didn't get a ping for this issue!  I'm about to release a new version and I'm going to figure out if this is an issue or not before releasing it.

**Comment by jmoiron** [comment]
I understand you've probably moved on by now but these are fixed in https://www.curseforge.com/minecraft/mc-mods/gregtech-extended-chemistry-extended/files/5950413 and will be fixed in qs 0.4.2

thanks for the report 🙇
