### ISSUE TITLE
Treated Wood Stick recipe conflicts with Stick recipe

### ISSUE THREAD

**Issue by aleats91** [jmoiron/quantum-skies#8]
I've been messing with the modpack for a day or so now, and got to the steam power phase. I tried to make a primitive pump, and for that I'd need treated wood sticks. However, when I tried to make the sticks, all I got was normal sticks, because the recipes for normal sticks and treated sticks are the exact same, and there is no way to choose between the two, as no mod that allows for that (such as Polymorph) is installed. For the meantime I'll just install Polymorph, but I'd definitely appreciate it if a more permanent solution was added to the pack.

**Comment by jmoiron** [comment]
Treated wood stick has an alt recipe but the conflict has also been fixed.  Not sure where it's coming from, but gtceu devs claimed it wasn't them.  Should work in 0.2.x
