### ISSUE TITLE
Steam Grinder does not parallelize

### ISSUE THREAD

**Issue by aleats91** [jmoiron/quantum-skies#9]
The Steam Grinder recipes do not seem to parallelize at all with the current build of GregTech Modern. From what I've seen, here seems to be a fix for it in [build 640](https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.2.1-build_640). Maybe it isn't the highest priority at the moment, as it doesn't really break progression or anything, but the steam grinder as it is now is fairly useless compared to just using a steam macerator.

**Comment by aleats91** [comment]
Apparently, build 640 and up does cause some problems with machines being unable to process any amount less that their maximum (i.e. the steam grinder and steam oven can only process exactly 8 items at a time). Newer versions do seem to have that fixed, but they are later than 1.2.2a, which is the latest version on curseforge and modrinth, and it's currently not possible to upgrade past build 642 because of some API changes that break the steam machines mod completely (in this version of the pack at least).

**Comment by jmoiron** [comment]
tested in latest, this should be fixed since may 🙇
